name: Security audit
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
        - name: Harden the runner (Audit all outbound calls)
          uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
          with:
            egress-policy: audit

        - uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee # v1.0.4
          with:
            go-version-input: 'stable'
            check-latest: true